backend:
  name: github
  repo: britthany-b/britthany.b
  branch: main

media_folder: "entradas/imagenes"
public_folder: "/entradas/imagenes"

collections:
  - name: "blog"
    label: "Entradas del Blog"
    folder: "entradas"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Imagen de Portada", name: "image", widget: "image", required: false }
      - { label: "Resumen corto", name: "description", widget: "text" }
      - { label: "Contenido de la entrada", name: "body", widget: "markdown" }
